version: "3.9"
services:
  eclipse-mosquitto:
    image: eclipse-mosquitto
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
    - "1883:1883"
    - "9001:9001"
  mosquitto-bezeroa:
    build: ..