apiVersion: v1
kind: Service
metadata:
  name: eclipse-mosquitto
  labels:
    component: mosquitto
spec:
  type: LoadBalancer
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    component: mosquitto